worker_processes auto;

events {
    worker_connections 1024;
}

http {

    limit_req_zone $binary_remote_addr zone=predict_limit:10m rate=10r/s;

    upstream api_v1 {
        server api-v1:8000;
    }
    upstream api_v2 {
        server api-v2:8000;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate     /etc/nginx/certs/nginx.crt;
        ssl_certificate_key /etc/nginx/certs/nginx.key;

        location /nginx_status {
            stub_status on;
            access_log off;
            allow 172.18.0.0/12;
            allow 127.0.0.1;
            deny all;
        }

        location /predict {
            auth_basic "API Access Protected";
            auth_basic_user_file /etc/nginx/.htpasswd;

            limit_req zone=predict_limit burst=20 nodelay;

            proxy_set_header Host            $host;
            proxy_set_header X-Real-IP       $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            if ($http_x_experiment_group = "debug") {
                proxy_pass http://api_v2;
            }
            proxy_pass http://api_v1;
        }
    }
}